apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-container
        image: 865170248675.dkr.ecr.ap-south-1.amazonaws.com/ecr-demo-1:latest
        ports:
        - containerPort: 8080
